# Generated by Django 6.0.5 on 2026-05-22 18:31

import django.db.models.deletion
import gestion_permisos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERMISO', 'Permiso General'), ('REPOSO', 'Reposo Médico')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='justificantes/', validators=[gestion_permisos.models.validar_extension_archivo])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones_admin', models.TextField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_permisos.trabajador')),
            ],
        ),
    ]
