# Generated by Django 6.0.5 on 2026-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='dias_continuos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='dias_laborables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('PERMISO', 'Permiso General'), ('REPOSO', 'Reposo Médico'), ('PERMISO_CUIDO_MATERNO', 'Permiso por Cuidado Materno'), ('PERMISO_CUIDO_PATERNO', 'Permiso por Cuidado Paterno'), ('PERMISO_DEPORTIVO', 'Permiso Deportivo'), ('INASISTENCIA_INJUSTIFICADA', 'Inasistencia Injustificada'), ('INASISTENCIA_JUSTIFICADA', 'Inasistencia Justificada')], max_length=30),
        ),
    ]
