# Generated by Django 6.0.5 on 2026-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_permisos', '0002_solicitud_dias_continuos_solicitud_dias_laborables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='password_reset_required',
            field=models.BooleanField(default=True),
        ),
    ]
