# Generated by Django 6.0.5 on 2026-05-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_permisos', '0003_trabajador_password_reset_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(default='', max_length=100, verbose_name='Ubicación Administrativa'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
