# Generated by Django 6.0.5 on 2026-05-29 11:27

import gestion_permisos.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_permisos', '0004_alter_trabajador_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cedula_encrypted',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='detalles',
            field=gestion_permisos.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='motivo',
            field=gestion_permisos.fields.EncryptedTextField(),
        ),
    ]
